name: R package

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  test:
    steps:
    - uses: actions/checkout@v2

    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()

    - name: Run tests
      shell: Rscript {0}
      run: |
        testthat::test_dir("./tests/testthat")
